require("lazy").setup({
	"williamboman/nvim-lsp-installer",
	"neovim/nvim-lspconfig",
	"numToStr/Comment.nvim",
	"majutsushi/tagbar",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-path",
	"hrsh7th/cmp-cmdline",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-vsnip",
	"hrsh7th/vim-vsnip",
	"rafamadriz/friendly-snippets",
	"onsails/lspkind-nvim",
	"sbdchd/neoformat",
	"Pocco81/auto-save.nvim",
	"b0o/schemastore.nvim",
	{
		"nvim-tree/nvim-tree.lua",
		dependencies = { "nvim-tree/nvim-web-devicons" },
	},
	"Mofiqul/dracula.nvim",
	"nvim-lualine/lualine.nvim",
	{
		"nvim-treesitter/nvim-treesitter",
		run = ":TSUpdate",
		dependencies = { "nvim-lua/plenary.nvim" },
	},
	"ellisonleao/glow.nvim",
	"akinsho/toggleterm.nvim",
	"rmagatti/auto-session",
	"windwp/nvim-autopairs",
	"ethanholz/nvim-lastplace",
	"akinsho/bufferline.nvim",
	"airblade/vim-gitgutter",
	"RRethy/vim-illuminate",
	{
		"iamcco/markdown-preview.nvim",
		run = function()
			vim.fn["mkdp#util#install"]()
		end,
	},
	{
		"turbio/bracey.vim",
		run = "npm install --prefix server",
	},
	{
		"nvim-telescope/telescope.nvim",
	},
	{ "nvim-telescope/telescope-file-browser.nvim" },
	{
		"nvim-telescope/telescope-fzf-native.nvim",
		run = "make",
	},
	"nvim-telescope/telescope-project.nvim",
	"simrat39/symbols-outline.nvim",
	{
		"junegunn/fzf",
		run = function()
			vim.fn["fzf#install"]()
		end,
	},
	"junegunn/fzf.vim",
	"isobit/vim-caddyfile",
	"dstein64/vim-startuptime",
	"folke/trouble.nvim",
	"j-hui/fidget.nvim",
	"github/copilot.vim",
	{ "lukas-reineke/indent-blankline.nvim", main = "ibl" },
})
